#!/usr/bin/env python3
"""Fail closed unless the Python 3.10 environment is exactly version/hash locked."""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "requirements.in"
LOCK = ROOT / "requirements.txt"
PYPROJECT = ROOT / "pyproject.toml"

EXPECTED_PYTHON_POLICY = ">=3.10,<3.11"
EXPECTED_BUILD_BACKEND = "setuptools.build_meta"
EXPECTED_LOCK_SHA256 = "57ae231da876909766a2cc84da110b71b4b37e9809ff4fd5a7bd416642c816df"
EXPECTED_GENERATOR_HEADER = (
    "# This file is autogenerated by pip-tools==7.6.1 with Python 3.10",
    "# by the following command (the package index is intentionally not embedded):",
    "#",
    "#    pip-compile --allow-unsafe --generate-hashes --no-emit-index-url --no-emit-trusted-host --output-file=requirements.txt --resolver=backtracking --strip-extras requirements.in",
)
EXPECTED_DIRECT_PINS = {
    "astropy": "5.3.4",
    "emcee": "3.1.6",
    "fast-histogram": "0.14",
    "flit-core": "3.12.0",
    "matplotlib": "3.7.5",
    "numpy": "1.23.5",
    "pandas": "1.5.3",
    "pip": "26.2.1",
    "pyyaml": "6.0.3",
    "requests": "2.34.2",
    "scipy": "1.10.1",
    "setuptools": "83.0.0",
    "tomli": "2.4.1",
    "wheel": "0.46.2",
}
EXPECTED_LOCKED_PINS = {
    "astropy": "5.3.4",
    "certifi": "2026.7.22",
    "charset-normalizer": "3.5.1",
    "contourpy": "1.3.2",
    "cycler": "0.12.1",
    "emcee": "3.1.6",
    "fast-histogram": "0.14",
    "flit-core": "3.12.0",
    "fonttools": "4.63.0",
    "idna": "3.19",
    "kiwisolver": "1.5.1",
    "matplotlib": "3.7.5",
    "numpy": "1.23.5",
    "packaging": "26.3",
    "pandas": "1.5.3",
    "pillow": "12.3.0",
    "pip": "26.2.1",
    "pyerfa": "2.0.1.5",
    "pyparsing": "3.3.2",
    "python-dateutil": "2.9.0.post0",
    "pytz": "2026.3.post1",
    "pyyaml": "6.0.3",
    "requests": "2.34.2",
    "scipy": "1.10.1",
    "setuptools": "83.0.0",
    "six": "1.17.0",
    "tomli": "2.4.1",
    "urllib3": "2.7.0",
    "wheel": "0.46.2",
}
EXPECTED_HASH_COUNTS = {
    "astropy": 29,
    "certifi": 2,
    "charset-normalizer": 172,
    "contourpy": 57,
    "cycler": 2,
    "emcee": 2,
    "fast-histogram": 9,
    "flit-core": 2,
    "fonttools": 50,
    "idna": 2,
    "kiwisolver": 141,
    "matplotlib": 47,
    "numpy": 28,
    "packaging": 2,
    "pandas": 27,
    "pillow": 87,
    "pip": 2,
    "pyerfa": 11,
    "pyparsing": 2,
    "python-dateutil": 2,
    "pytz": 2,
    "pyyaml": 73,
    "requests": 2,
    "scipy": 21,
    "setuptools": 2,
    "six": 2,
    "tomli": 47,
    "urllib3": 2,
    "wheel": 2,
}

DIRECT_PIN_RE = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s;\\]+)$")
LOCK_PIN_RE = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s;\\]+)\s+\\$")
HASH_RE = re.compile(r"^--hash=sha256:([0-9a-f]{64})(\s+\\)?$")


def fail(message: str) -> None:
    raise SystemExit(f"DEPENDENCY LOCK FAIL: {message}")


def normalized(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _toml_loads(text: str) -> dict[str, Any]:
    """Parse TOML with a real parser on both Python 3.10 and newer runtimes."""

    try:
        import tomllib as toml_parser  # type: ignore[import-not-found]
    except ModuleNotFoundError:
        try:
            import tomli as toml_parser  # type: ignore[import-not-found,no-redef]
        except ModuleNotFoundError:
            fail(
                "the directly locked tomli parser is required on Python 3.10"
            )
    try:
        parsed = toml_parser.loads(text)
    except Exception as exc:
        fail(f"pyproject.toml is not valid TOML: {exc}")
    if not isinstance(parsed, dict):
        fail("pyproject.toml root is not a table")
    return parsed


def _parse_pin_values(values: Any, context: str) -> dict[str, str]:
    if not isinstance(values, list):
        fail(f"{context} is not a TOML array")
    pins: dict[str, str] = {}
    for value in values:
        if not isinstance(value, str):
            fail(f"{context} contains a non-string entry: {value!r}")
        match = DIRECT_PIN_RE.fullmatch(value)
        if match is None:
            fail(f"{context} is not an exact == pin: {value!r}")
        name, version = normalized(match.group(1)), match.group(2)
        if name in pins:
            fail(f"duplicate {context} dependency {name!r}")
        pins[name] = version
    return pins


def direct_pins_from_text(text: str) -> dict[str, str]:
    pins: dict[str, str] = {}
    for line_number, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = DIRECT_PIN_RE.fullmatch(line)
        if match is None:
            fail(f"requirements.in:{line_number} is not an exact == pin: {line!r}")
        name, version = normalized(match.group(1)), match.group(2)
        if name in pins:
            fail(f"duplicate direct dependency {name!r}")
        pins[name] = version
    if not pins:
        fail("requirements.in contains no dependencies")
    return pins


def direct_pins() -> dict[str, str]:
    return direct_pins_from_text(INPUT.read_text(encoding="utf-8"))


def pyproject_pins_from_text(text: str) -> tuple[dict[str, str], dict[str, str]]:
    document = _toml_loads(text)
    build = document.get("build-system")
    project = document.get("project")
    if not isinstance(build, dict) or not isinstance(project, dict):
        fail("pyproject.toml lacks build-system or project tables")

    if build.get("build-backend") != EXPECTED_BUILD_BACKEND:
        fail(
            "pyproject build-backend is not exactly "
            f"{EXPECTED_BUILD_BACKEND!r}: {build.get('build-backend')!r}"
        )
    if "backend-path" in build:
        fail("pyproject build-system must not define backend-path")
    if project.get("requires-python") != EXPECTED_PYTHON_POLICY:
        fail(
            "pyproject requires-python policy changed: "
            f"{project.get('requires-python')!r} != {EXPECTED_PYTHON_POLICY!r}"
        )
    if "optional-dependencies" in project:
        fail("pyproject optional dependencies are not covered by the release lock")
    if "dependency-groups" in document:
        fail("pyproject dependency groups are not covered by the release lock")
    dynamic = project.get("dynamic", [])
    if not isinstance(dynamic, list) or dynamic:
        fail("pyproject release metadata must not use dynamic fields")

    project_pins = _parse_pin_values(project.get("dependencies"), "project dependency")
    build_pins = _parse_pin_values(build.get("requires"), "build dependency")
    return project_pins, build_pins


def pyproject_pins() -> tuple[dict[str, str], dict[str, str]]:
    return pyproject_pins_from_text(PYPROJECT.read_text(encoding="utf-8"))


def locked_pins_from_text(text: str) -> tuple[dict[str, str], dict[str, int]]:
    observed_lock_sha256 = hashlib.sha256(text.encode("utf-8")).hexdigest()
    if observed_lock_sha256 != EXPECTED_LOCK_SHA256:
        fail(
            "requirements.txt content digest changed: "
            f"{observed_lock_sha256} != {EXPECTED_LOCK_SHA256}"
        )
    lines = text.splitlines()
    if tuple(lines[: len(EXPECTED_GENERATOR_HEADER)]) != EXPECTED_GENERATOR_HEADER:
        fail("requirements.txt lacks the exact audited pip-tools generator header")

    pins: dict[str, str] = {}
    hashes: dict[str, list[tuple[str, bool]]] = {}
    seen_hashes: dict[str, str] = {}
    current: str | None = None

    for line_number, raw in enumerate(
        lines[len(EXPECTED_GENERATOR_HEADER) :],
        len(EXPECTED_GENERATOR_HEADER) + 1,
    ):
        stripped = raw.strip()
        pin_match = LOCK_PIN_RE.fullmatch(stripped)
        if pin_match is not None:
            if current is not None:
                fail(
                    f"requirements.txt:{line_number} starts a new package before "
                    f"the hash list for {current!r} is complete"
                )
            name, version = normalized(pin_match.group(1)), pin_match.group(2)
            if name in pins:
                fail(f"duplicate locked dependency {name!r}")
            pins[name] = version
            hashes[name] = []
            current = name
            continue

        hash_match = HASH_RE.fullmatch(stripped)
        if hash_match is not None:
            if current is None:
                fail(f"requirements.txt:{line_number} has a hash without a package")
            digest = hash_match.group(1)
            if digest in seen_hashes:
                fail(
                    f"requirements.txt:{line_number} repeats SHA-256 {digest} "
                    f"already assigned to {seen_hashes[digest]!r}"
                )
            seen_hashes[digest] = current
            continued = hash_match.group(2) is not None
            hashes[current].append((digest, continued))
            if not continued:
                current = None
            continue

        if current is not None:
            fail(
                f"requirements.txt:{line_number} interrupts the hash list for "
                f"{current!r}: {stripped!r}"
            )
        if stripped and not stripped.startswith("#"):
            fail(
                f"requirements.txt:{line_number} contains a forbidden or "
                f"unrecognized entry: {stripped!r}"
            )

    if current is not None:
        fail(f"requirements.txt ends before the hash list for {current!r} is complete")
    hash_counts = {name: len(entries) for name, entries in hashes.items()}
    if pins != EXPECTED_LOCKED_PINS:
        fail(
            "requirements.txt differs from the audited dependency closure: "
            f"observed={pins}, expected={EXPECTED_LOCKED_PINS}"
        )
    if hash_counts != EXPECTED_HASH_COUNTS:
        fail(
            "requirements.txt SHA-256 coverage differs from the audited lock: "
            f"observed={hash_counts}, expected={EXPECTED_HASH_COUNTS}"
        )
    return pins, hash_counts


def locked_pins() -> tuple[dict[str, str], dict[str, int]]:
    return locked_pins_from_text(LOCK.read_text(encoding="utf-8"))


def main() -> None:
    direct = direct_pins()
    project, build = pyproject_pins()
    locked, hash_counts = locked_pins()

    if direct != EXPECTED_DIRECT_PINS:
        fail(
            "requirements.in differs from the audited direct dependency policy: "
            f"observed={direct}, expected={EXPECTED_DIRECT_PINS}"
        )

    environment_only = {
        "flit-core",
        "pip",
        "pyyaml",
        "setuptools",
        "tomli",
        "wheel",
    }
    runtime_direct = {
        name: version
        for name, version in direct.items()
        if name not in environment_only
    }
    if project != runtime_direct:
        fail(
            "pyproject runtime dependencies differ from requirements.in: "
            f"project={project}, input={runtime_direct}"
        )
    if build != {"setuptools": direct["setuptools"]}:
        fail(f"pyproject build dependency is not the locked setuptools pin: {build}")
    if locked != EXPECTED_LOCKED_PINS:
        fail(
            "requirements.txt differs from the audited dependency closure: "
            f"observed={locked}, expected={EXPECTED_LOCKED_PINS}"
        )
    if hash_counts != EXPECTED_HASH_COUNTS:
        fail(
            "requirements.txt SHA-256 coverage differs from the audited lock: "
            f"observed={hash_counts}, expected={EXPECTED_HASH_COUNTS}"
        )

    print(
        "PASS dependency lock "
        f"({len(direct)} direct; {len(locked)} total; "
        f"{sum(hash_counts.values())} SHA-256 hashes)"
    )


if __name__ == "__main__":
    main()
